### ISSUE TITLE
Lightmap uvw has broken export

### ISSUE THREAD

**Issue by HuntersRun1** [seedhartha/kotorblender#8] opened 2021-12-07 22:27 UTC
To reproduce import an area model and apply a lightmap pack( size 512, quality 48, margin 0.5). Export and  reimport the model and look at the lightmap uvw.

edit: It appears to be a blender problem not a kotorblender problem as lightmap pack is a blender option.

**Comment by HuntersRun1** [comment] 2022-02-13 02:10
It appears that while this is a blender option using lightmap pack will break custom lightmaps. This only happens with a mdl export (not  fbx or other export).  While it is possible to create lightmaps without lightmap pack, lightmap pack does give the best looking  results( hence the name).

**Comment by seedhartha** [comment] 2022-04-06 00:15
Not sure I follow, some images would be welcome. I've used lightmap pack myself, and while sometimes there were artifacts, I could easily solve those by tweaking pack parameters and/or splitting into multiple lightmaps by relative surface size.

**Comment by HuntersRun1** [comment] 2022-04-06 16:58
before export:
![H5_Walls1](https://user-images.githubusercontent.com/18150181/162027464-a4ca7524-6c66-4217-a250-d68fdd7bdf48.png)

after export:

![H5_Walls1a](https://user-images.githubusercontent.com/18150181/162027553-7e5b5e9d-318e-4726-aa7d-042075489134.png)

More testing shows that it is the way vertex's are connected that is the issue.  To clarify two that are separated at the same location will not have any issues. However two that are connected and have different uvw maps applied to them will run into this issue.

**Comment by seedhartha** [comment] 2022-04-07 03:28
I still don't follow. If vertices are connected then they are of the same object. An object can only have one lightmap UV map. When you need one vertex to have different UV coordinates for different faces, then you must split it.

> To reproduce import an area model and apply a lightmap pack( size 512, quality 48, margin 0.5). Export and reimport the model and look at the lightmap uvw.

Tried that, UV map was good.

**Comment by seedhartha** [comment] 2022-04-07 04:17
Ok, I see what the problem is. In MDL UV coordinates are per vertex, but in Blender they are per edge loop. There are as many edge loops per vertex as there are triangles. Now the problem is that lightmap pack in Blender assigns multiple UV coordinates to each vertex.

![lightmap-pack-uv-bug](https://user-images.githubusercontent.com/7695218/162118840-5eee8059-1e7a-4b57-9bdb-e431766e5ef1.jpeg)

That is not something I can trivially fix, unfortunately. One solution would be to detect these anomalies on export and duplicate vertices.

**Comment by seedhartha** [comment] 2023-12-26 20:03
Should be fixed by 0bca7bca80583c307ae2bd9f228c833181cd3e8d. Vertices are now automatically duplicated on export when corresponding edge loops have different normals or UV coordinates.

**Closed as completed by seedhartha** 2023-12-26 20:03 UTC
